@startuml
'https://plantuml.com/state-diagram
hide empty description
'scale 350 width

[*] --> ConnectionWait
ConnectionWait --> SendGreeting : accept()
SendGreeting --> LoginWait : TextMsg>

LoginWait --> CheckLogin : >LoginMsg
LoginWait --> SendGreeting : >all other msgs
CheckLogin --> SendLoginConfirm : valid
SendLoginConfirm --> CmdWait : TextMsg>
CheckLogin --> SendLoginFail : invalid
SendLoginFail --> SendGreeting : TextMsg>

CmdWait -up-> SendGoodbye : >LogoutMsg
SendGoodbye -up-> ConnectionWait : TextMsg>

CmdWait --> BuildHelpReply : >HelpMsg
CmdWait --> BuildUserListReply : >ListUsersMsg
CmdWait --> SetOption : >OptionMsg w/ setting
CmdWait --> BuildOptionReply : >OptionMsg w/o setting
SetOption --> BuildOptionReply

''''''''''
'CmdWait --> SaveFile : >FileMsg
'SaveFile --> BuildSaveOKReply
'SaveFile --> BuildSaveFailReply
'BuildSaveOKReply --> SendReply
'BuildSaveFailReply --> SendReply
CmdWait --> filedc : >FileMsg

state "FileMsg Handling Choice" as filedc {
    [*] --> SaveFile
    SaveFile --> BuildOKReply : succeed
    SaveFile --> BuildFailReply : fail
    --
    [*] --> BuildTextAckReply
    --
    [*] --> BuildFileReply
}
filedc --> SendReply


''''''''''
CmdWait --> BuildEchoReply : >TextMsg
BuildHelpReply --> SendReply
BuildUserListReply --> SendReply
BuildOptionReply --> SendReply
BuildEchoReply --> SendReply

SendReply --> CmdWait : TextMsg or\n FileMsg>

@enduml